# -*- coding: utf-8 -*-
"""Code_to_Find_the_Area_of_Shapes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OFLCaB0W5Z4ZFlF_U7_Phr_gmp5lX3Te

# Finding the Area of Shapes with Python
1. Calculate the area of circle
take pi as constant value 3.14
take radius as input in float
the final area must be in integer

2. Calculating the area of any 3 other shapes using input function

## Solutions
"""

# 1. Calculate the area of circle
'''
take pi as constant value 3.14
take radius as input in float
the final area must be in integer
'''
# A = πr2, where r is the radius and π is approximately 3.14159.
# www.math.net › area-of-a-circle Area of a circle - Math.net
pi = 3.14159
r = float(input('Enter your radius (r) value: '))
A = int(pi * (r**2))

print('Area of a circle is ', A)

print(type(r))
print(type(A))

# 2. Take any 3 shapes and calculate their areas using input function

# i. Rectangle
L = float(input('Enter length value here: '))
B = float(input('Enter breadth value here: '))
Area = L * B

print('Area of the Rectangle is ', Area)

# ii. Tringle
# Formula: A = 1/2 * B*H
B = float(input('Enter value for base (B): '))
H = float(input('Enter value for height (H): '))
A = (1/2 * (B * H))

print('Area of your Triangle is ', A)

# Square
# Formula: A = s**2
S = float(input('Enter the value of the length: '))
A = S**2

print('Area of your Square is ', A)